version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    restart: on-failure
    ports:
      - "8001:8000"
    command: /start-fastapi
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  aiogram:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    restart: on-failure
    command: /start-aiogram
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  scheduler:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: /start-scheduler
    volumes:
      - ./backend:/app
    depends_on:
      - web

  mongodb:
    image: mongo:7.0.5
    ports:
      - 27037:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


